apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gateway.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
type: Opaque
stringData:
  ENCRYPTION_KEY: {{ .Values.secrets.ENCRYPTION_KEY }}
  JWT_SECRET: {{ .Values.secrets.JWT_SECRET }}
  JWT_REFRESH_SECRET: {{ .Values.secrets.JWT_REFRESH_SECRET }}
  GOOGLE_CLIENT_ID: {{ .Values.secrets.GOOGLE_CLIENT_ID }}
  GOOGLE_CLIENT_SECRET: {{ .Values.secrets.GOOGLE_CLIENT_SECRET }}
  GITHUB_CLIENT_ID: {{ .Values.secrets.GITHUB_CLIENT_ID }}
  GITHUB_CLIENT_SECRET: {{ .Values.secrets.GITHUB_CLIENT_SECRET }}
  MONGODB_URI: {{ .Values.secrets.MONGODB_URI }}
  REDIS_URL: {{ .Values.secrets.REDIS_URL }}